remote_theme: "mmistakes/minimal-mistakes@4.16.6"
title: "Arnaud Sahuguet"
subtitle: ""
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: https://linkedin.com/sahuguet
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/sahuguet
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/sahuguet

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true